#!/bin/bash

# Creates a backup file of the source_file with the extension .bak

if [ -z $1 ]; then
  echo "usage: bak source_file"
  exit 1
fi

if [ -e $1 ]; then
  cp $1{,.bak}
else
  echo "$1 does not exist"
  exit 1
fi

