#!/bin/bash

function usage() {
  echo "usage: ps-translate [svn]"
}

SVN_UP=""
if [ $1="svn" ]; then
  SVN_UP=true
fi

if [ ! $PERSONA_ROOT ]; then
  echo "PERSONA_ROOT not specified"
  exit 1
fi

pushd $PERSONA_ROOT

if [ $SVN_UP ]; then 
  echo "Updating SVN repo"
  svn co -q http://svn.mozilla.org/projects/l10n-misc/trunk/browserid/locale
  cd locale
  svn up
  cd ..

  for file in locale/templates/LC_MESSAGES/*.pot ; do
      mv $file $file.old
      sed 's/CHARSET/UTF-8/g' $file.old > $file
      rm -f $file.old
  done
fi

echo "Extracting PO files"
./scripts/extract_po.sh locale

echo "Merging PO files"
./scripts/merge_po.sh locale

echo "Compiling MO files"
./locale/compile-mo.sh locale

echo "Creating JSON files"
./locale/compile-json.sh locale resources/static/i18n

popd

